lmp/jobserve: update imx8mm and imx8mq machine names
foundriesio/ci-scripts pull request #146
Opened 2021-09-20 23:30 UTC by ricardosalveti

Use the new names as available starting from OE / Yocto hardknott.

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

2021-09-20 23:43 UTC, mike-scott approved these changes
LGTM

2021-09-20 23:46 UTC, mike-scott requested changes
@ricardosalveti There are 2 more references in jobserv.yml.  Are we keeping those on the old machine name for some reason?

2021-09-20 23:48 UTC, mike-scott approved these changes
Per discussion on Slack, keeping the old machine names in place for stable testing.
LGTM

2021-09-21 14:06 UTC, angolini approved these changes

2021-09-21 14:08 UTC, vanmaegima approved these changes

2021-09-21 14:12 UTC, merged